Upload progress feature for explore submissions
QasimWani/LeetHub pull request #120
Opened 2021-08-11 17:02 UTC by sbibek

Added support for submissions on explore page. Error handlers in place so that errors won't break existing features. Also fix avoids note on explore section as there are none.

2021-08-12 06:29 UTC, QasimWani requested changes

2021-08-12 06:29 UTC, QasimWani commented on scripts/leetcode.js
> +    target = document.getElementsByClassName('action')[0].getElementsByClassName('row')[0].getElementsByClassName('col-sm-6')[1]
assumption ur making here is all these fields are available. u need to do null check for this, unless this is guaranteed to be present within leetcode. plz verify the ubiquity of this structure @sbibek

2021-08-12 18:33 UTC, sbibek reviewed
Cardinality checks for all the elements used are now made.

2021-08-14 02:20 UTC, QasimWani reviewed
plz see comments.

2021-08-14 02:20 UTC, QasimWani commented on scripts/leetcode.js
> +    if (!elem) {
this seems the opposite to what was done before. `!elem` tells me that if that element is not present, create the spinner. But previously, you had it as if the element was present, create a spinner.
reason? @sbibek

2021-08-14 22:28 UTC, sbibek reviewed
It's the fix for the unsound logic that was there but worked due to the reason null != undefined

2021-08-18 20:49 UTC, QasimWani approved these changes

2021-08-19 13:53 UTC, merged