added mozilla addon link to the readme
QasimWani/LeetHub pull request #392
Opened 2022-10-20 13:18 UTC by ArjixWasTaken

and improved the readme a bit, just a tiny bit

2022-10-20 13:19 UTC, ArjixWasTaken commented
![image](https://user-images.githubusercontent.com/53124886/196959614-fd9b075f-b229-4753-a611-79f6041400ee.png)

2022-10-20 13:19 UTC, ArjixWasTaken commented
unless the mozilla addon is unofficial...i dont really know

2022-10-20 13:21 UTC, ArjixWasTaken commented
PS: the mozilla image I used is an edit of chrome's badge, and I allow you to use it

2022-10-20 23:14 UTC, QasimWani commented
This is cool. Yeah the Firefox version is a fork developed by @njelich which is community driven. There's no such thing as official and official. Pretty decentralized when it comes to the that 😉

2022-10-21 15:33 UTC, QasimWani requested changes

2022-10-21 15:33 UTC, QasimWani commented on README.md
> +  <a href="https://github.com/QasimWani/LeetHub">LeetHub</a> - Automatically sync your code to GitHub.
replace with chrome webstore URL – https://chrome.google.com/webstore/detail/leethub/aciombdipochlnkbpcbgdpjffcfdbggi

2022-10-30 08:37 UTC, aashu commented
@QasimWani I tried loading leethub directly from this repo and it was working without any issues. So I don't think there is any requirement to maintain a seperate fork for firefox. Also, the fork you are talking about doesn't seems to be updated since April. It would be great if we can use this repo only and list extension to firefox addons store.

2022-10-30 20:01 UTC, njelich commented
@aashu Yep, my changes added compatibility and it was merged to the main repo.

2022-10-31 20:08 UTC, merged