Full solution not being committed, bottom portion is being cropped out. #62(Solved)
QasimWani/LeetHub pull request #64
Opened 2021-01-20 12:56 UTC by mahbubcseju

In some cases, it failed to commit full code. Please see the issue number #62 for details. I solved this issue by fetching the code from the individual submission details page.

2021-01-25 16:36 UTC, QasimWani commented on scripts/leetcode.js
> +            var code = codeUnicoded.replace(/\\u[\dA-F]{4}/gi,
explain regex?

2021-01-25 16:38 UTC, QasimWani requested changes
thanks for the PR!
can you add some comments on your function? also, have you passed all eslint tests? We require you to lint before I can merge. keeps everything standardized. see readme for description.

2021-01-25 16:38 UTC, QasimWani commented on scripts/leetcode.js
> +function findCode(
could you comment main parts of this function?
thanks

2021-01-26 06:02 UTC, mahbubcseju commented
I added some comments and ran lint test. Thanks

2021-01-26 14:30 UTC, QasimWani approved these changes
lgtm!
good job :D
also, next time, make sure to send PR to dev branch instead of main. @mahbubcseju

2021-01-26 14:30 UTC, merged